server:
  port: 8081

spring:
  datasource:
    username: nikita
    password: nikita
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

auth:
  jwt:
    secret: "30faa058f27f690c7e9a098d54ebcfb3d8725bcb85ee7907a2d84c69622229e2:"
